// Débogage
/*
	function positionSouris(evt) {
	   var x = character.xPos;
	   var y = character.yPos;
	   var dada = character.model.clientX;
	   var vava = character.model.clientY;
	   d.innerHTML = 'character :<br>x = ' + x + '<br>y = ' + y +'<br>dada :<br>x = ' + dada + '<br>y = ' + vava;   
	}

	function changePositionDiv(evt) {
		d.style.top = (evt.clientY+10) + 'px';
		d.style.left = (evt.clientX+10) + 'px';
	}

	var b = document.body;
	var d = document.getElementById('divPosition');

	// l'événement 'mousemove' est associé à 2 actions différentes
	b.addevtListener('mousemove',positionSouris);
	b.addevtListener('mousemove',changePositionDiv);

*/
//Variable globales pour ne pas avoir à connaitre les numérosdes touches par coeur.
		LEFTKEY 	= 37;
		RIGHTKEY	= 39;
		UPKEY		= 38;
		DOWNKEY		= 40;

		ZKEY		= 90;
		QKEY		= 81;
		SKEY		= 83;
		DKEY		= 68;

		WKEY		= 87;
		AKEY		= 65;
		SPACEKEY	= 32;

		F5KEY		= 116;
		F12KEY      = 123;
		ECHAPKEY    = 27;
		ENTERKEY	= 13


	    HAUT 		= 0;
	    BAS 		= 1;
	    GAUCHE 		= 2;
	    DROITE 		= 3;
	    HG			= 5;
	    HD			= 9;
	    BG			= 6;
	    BD			= 10;


RIEN=0;
PERS=1;
BRIC=2;
ENNH=3;
ENNB=4;
ENNG=5;
ENND=6;
TRES=7;

//Ce niveau ne sert à rien à part à être copier-coller.
var lvl0=[
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN]
];

var lvl1=[
[PERS, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, ENNB, RIEN, RIEN, RIEN, ENND, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, BRIC],
[RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, BRIC],
[BRIC, RIEN, BRIC, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN],
[BRIC, RIEN, BRIC, BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENND],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNH, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNB, RIEN, RIEN, RIEN, BRIC, RIEN],
[ENNG, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, BRIC, RIEN, BRIC],
[RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, ENNH, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN],
[ENNH, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, TRES]
];

var lvl2=[
[PERS, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, BRIC, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNH, BRIC, ENNB, BRIC, ENND, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, BRIC, ENNH, BRIC, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, ENND, ENNG, TRES, ENND, ENNG, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, BRIC, ENNB, BRIC, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, BRIC, ENNH, BRIC, ENNB, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, BRIC, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN]
];

var lvl3=[
[BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC],
[PERS, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, TRES, RIEN],
[BRIC, ENNH, BRIC, ENNH, BRIC, ENNH, BRIC, ENNH, BRIC, ENNH, ENNH, BRIC, ENNH, BRIC, ENNH, BRIC, ENNH, BRIC, ENNH, BRIC],
];

var lvl4=[
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, PERS],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC],
[RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, ENNG],
[BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC],
[ENND, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN],
[RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, ENNG],
[BRIC, BRIC, RIEN, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC],
[ENND, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNG],
[BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN],
[RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN],
[BRIC, BRIC, RIEN, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC],
[RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN],
[RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, RIEN, BRIC, BRIC, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN],
[BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC],
[TRES, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNH, RIEN, RIEN, RIEN]
];

var lvl5=[
[PERS, RIEN, RIEN, BRIC, RIEN, ENNB, ENNB, RIEN, BRIC, RIEN, ENNB, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN],
[BRIC, RIEN, BRIC, BRIC, RIEN, RIEN, RIEN, RIEN, BRIC, BRIC, RIEN, BRIC, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, BRIC, RIEN, BRIC, BRIC, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, BRIC, RIEN, BRIC, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, ENNH, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN],
[BRIC, RIEN, BRIC, BRIC, RIEN, RIEN, RIEN, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN],
[RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, RIEN, RIEN],
[RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNB, BRIC, RIEN, BRIC],
[RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN],
[RIEN, RIEN, ENNH, BRIC, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, ENNH, RIEN, BRIC, ENNH, BRIC, RIEN, RIEN, BRIC, ENNH, TRES]
];

var lvl42=[
[BRIC, PERS, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, RIEN, TRES],
[BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, ENNB, BRIC, ENNB, RIEN, ENNB, BRIC, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, ENNG],
[BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN],
[BRIC, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN],
[RIEN, BRIC, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN],
[RIEN, BRIC, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN],
[RIEN, BRIC, BRIC, ENNH, BRIC, ENNH, RIEN, RIEN, RIEN, ENNH, BRIC, ENNH, BRIC, ENNH, RIEN, ENNH, BRIC, RIEN, RIEN, RIEN],
[RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC],
[RIEN, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, ENNG],
[BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, BRIC, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, BRIC, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, ENNH, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, RIEN, ENNG]
];

var lvl124=[
[BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC],
[BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, BRIC],
[BRIC, PERS, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, BRIC],
[BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, BRIC],
[BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC],
[BRIC, RIEN, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC],
[BRIC, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC],
[BRIC, RIEN, BRIC, BRIC, RIEN, BRIC, BRIC, RIEN, BRIC, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC],
[BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, BRIC, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC],
[BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, RIEN, TRES],
[BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, RIEN, BRIC],
[BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC],
[BRIC, RIEN, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC],
[BRIC, RIEN, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC],
[BRIC, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC],
[BRIC, RIEN, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC],
[BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, BRIC],
[BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, BRIC],
[BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, BRIC],
[BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC]
];

var lvl69=[
[TRES, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN],
[RIEN, BRIC, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, BRIC, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN],
[BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNH, ENNH, ENNH, ENNH, ENNH, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, BRIC, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN],
[RIEN, RIEN, RIEN, BRIC, RIEN, ENNG, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENND, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, ENND, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, BRIC, RIEN, RIEN, ENNG, BRIC, RIEN, RIEN, PERS, RIEN, RIEN, BRIC, ENND, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, ENND, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENND, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, BRIC, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNB, ENNB, ENNB, ENNB, ENNB, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN],
[RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC],
[RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN],
[BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC]
];

var lvl792=[
[ENND, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, BRIC],
[RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, BRIC],
[RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, BRIC],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC],
[RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, BRIC],
[ENND, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, ENNG, BRIC],
[BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC],
[BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, ENNG, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC],
[BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, RIEN, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC],
[PERS, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, ENNH, ENNG, ENNH, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, TRES],
[BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, RIEN, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC],
[BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, ENNG, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC],
[BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC],
[ENND, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, BRIC],
[RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, BRIC],
[RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC],
[BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC],
[ENND, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, ENNG, BRIC],
[RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC],
[BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC]
];

var lvlm12=[
[RIEN, RIEN, RIEN, RIEN, RIEN, ENNB, BRIC, BRIC, BRIC, PERS, BRIC, BRIC, BRIC, ENNB, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, BRIC, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNH, RIEN, ENNH, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNH, BRIC, RIEN, BRIC, ENNH, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNH, BRIC, RIEN, RIEN, RIEN, BRIC, ENNH, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, ENNH, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, ENNH, ENNH, ENNH, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, ENNH, RIEN],
[ENNH, BRIC, ENNH, ENNH, ENNH, ENNH, ENNH, ENNH, ENNH, TRES, ENNH, ENNH, ENNH, ENNH, ENNH, ENNH, ENNH, ENNH, BRIC, ENNH]
];

var lvl666=[
[PERS, RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, BRIC, RIEN, RIEN, RIEN, ENNG, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN],
[RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN],
[RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, BRIC, BRIC, BRIC, RIEN],
[RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, RIEN, RIEN, BRIC, ENNB, ENNB, BRIC, RIEN],
[RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, BRIC, ENNB, ENNB, BRIC, RIEN],
[RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, BRIC, RIEN, RIEN, BRIC, RIEN, BRIC, ENNB, ENNB, BRIC, RIEN],
[RIEN, RIEN, BRIC, RIEN, BRIC, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, BRIC, BRIC, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN],
[RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, BRIC, RIEN, RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, ENNH, ENNH, BRIC, RIEN],
[RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, BRIC, BRIC, BRIC, RIEN, BRIC, ENNH, ENNH, BRIC, RIEN],
[RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, ENNH, ENNH, BRIC, RIEN],
[RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN],
[RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, BRIC, BRIC, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN],
[RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN],
[RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, BRIC, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN],
[RIEN, BRIC, ENNH, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, RIEN, BRIC, RIEN],
[RIEN, BRIC, BRIC, BRIC, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, ENNG, RIEN, BRIC, RIEN],
[RIEN, BRIC, ENND, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, BRIC, BRIC, RIEN, RIEN, RIEN, TRES, RIEN, ENNG, RIEN, BRIC, RIEN],
[ENNH, RIEN, BRIC, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, ENNG, RIEN, BRIC, RIEN],
[BRIC, RIEN, BRIC, RIEN, RIEN, BRIC, RIEN, BRIC, RIEN, RIEN, RIEN, RIEN, BRIC, RIEN, RIEN, RIEN, BRIC, RIEN, BRIC, ENNH],
[BRIC, RIEN, RIEN, RIEN, BRIC, BRIC, RIEN, RIEN, RIEN, BRIC, BRIC, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, RIEN, BRIC, ENNH]
];

//Variables servant à relancer la partie.
var charXPosInitial = 0;
var charYPosInitial = 0;

var ennemisXPosInitial = [];
var ennemisYPosInitial = [];
var ennemisDirectionInitiale = [];

var protege=false;

function loop(timestamp) {
	if (!jeu_commence)
		return false;
	var progress = timestamp - lastRender;

	time+=progress;
	update();
	draw();
	lastRender = timestamp;
	window.requestAnimationFrame(loop);
}

function init(){
	niveauEnCours=""
	jeu_commence = false;
	time = 0;
    lastRender = 0;
    window.requestAnimationFrame(loop);

    character = {
    	speed: 2,
    	xPos:0,
    	yPos:0,
    	width: 20,
    	height: 20,
    	direction: BAS,
    	model: document.createElement('img')
    };

    tresor = {
    	xPos:0,
    	yPos:380,
    	width: 20,
    	height: 20,
    	model: document.createElement('img')
    };
    keys = {};

	document.body.onkeyup = 
	document.body.onkeydown = function(evt){
		evt = evt || window.evt;
		var charCode = evt.keyCode || evt.which;
		if (charCode != F12KEY && (charCode<96 || charCode >105) && charCode !=8 && charCode != F5KEY)
			evt.preventDefault();
		if((charCode==ENTERKEY||charCode==SPACEKEY) && evt.type == 'keydown'){
			if(jeu_commence){
				jeu_commence=false;
			}else{
				jeu_commence=true;
				window.requestAnimationFrame(loop);
			}
		}
		keys[charCode]= evt.type == 'keydown';
	};



    game_container = document.getElementById("game_container");
    debut_partie = document.getElementById("debut_partie");
    protection = document.getElementById("protection");
    protection.onclick = function(event){
    	if (protege){
    		protection.innerHTML="Protection de la princesse Alpacorn désactivée";
    		protege=false;
    	}else{
    		protection.innerHTML="Protection de la princesse Alpacorn activée";
    		protege=true;
    	}
    }

    tab_briques = [];
	nbBriques = 0;

    tab_ennemis = [];
    nbEnnemis = 0;
    chargerNiveau();

    debut_partie.onclick=function(evt){
    	if(!jeu_commence){
	    	jeu_commence=true;
	    	window.requestAnimationFrame(loop);
    	}
    }

    document.getElementById("charger_niveau").onclick = function(evt){
    	switch (document.getElementById("lvl_select").value){
    		case "1":
    			niveauEnCours="1";
    			chargerNiveau(lvl1);
    			break;
    		case "2":
    			niveauEnCours="2";
    			chargerNiveau(lvl2);
    			break;
    		case "3":
    			niveauEnCours="3";
    			chargerNiveau(lvl3);
    			break;
    		case "4":
    			niveauEnCours="4";
    			chargerNiveau(lvl4);
    			break;
    		case "5":
    			niveauEnCours="5";
    			chargerNiveau(lvl5);
    			break;
    		case "42":
    			niveauEnCours="42";
    			chargerNiveau(lvl42);
    			break;
    		case "124":
    			niveauEnCours="124";
    			chargerNiveau(lvl124);
    			break;
    		case "69":
    			niveauEnCours="69";
    			chargerNiveau(lvl69);
    			break;
    		case "792":
    			niveauEnCours="792";
    			chargerNiveau(lvl792);
    			break;
    		case "-12":
    			niveauEnCours="-12";
    			chargerNiveau(lvlm12);
    			break;
    		case "666":
    			niveauEnCours="666";
    			chargerNiveau(lvl666);
    			break;
    		default:
    			niveauEnCours="";
    			chargerNiveau();
    			break;
    	}
    }

    document.getElementById("niveau_random").onclick = function(evt){
    	chargerNiveau();
    }
}









function chargerNiveau(args){
	tab_ennemis=[];
	tab_briques=[];
	nbBriques=0;
	nbEnnemis=0;
	if (typeof chargerNiveau.arguments[0] !="undefined"){
		chargerNiveauPredefini(chargerNiveau.arguments[0]);
	}else{
		chargerNiveauRandom();
	}
}


function chargerNiveauPredefini(niveau){
	keys={};
	game_container.innerHTML="";
	for(var y=0; y<20; y++){
		for(var x=0; x<20; x++){
			switch (niveau[y][x]){
				case PERS:
					preparePersonnage(20*x, 20*y);
					break;
				case TRES:
					prepareTresor(20*x,20*y);
					break;
				case BRIC:
					prepareBrique(20*x, 20*y);
					break;
				case ENNH:
					prepareEnnemi(20*x, 20*y, HAUT);
					break;
				case ENNB:
					prepareEnnemi(20*x, 20*y, BAS);
					break;
				case ENNG:
					prepareEnnemi(20*x, 20*y, GAUCHE);
					break;
				case ENND:
					prepareEnnemi(20*x, 20*y, DROITE);
					break;
			}
		}
	}

    affichePersonage();
    afficheTresor();
    afficheBriques();
    afficheEnnemis();
}


function chargerNiveauRandom(){
	keys={};
	game_container.innerHTML="";
    preparePersonnage();
    prepareTresor();
    prepareBriques();
    prepareEnnemis();

    affichePersonage();
    afficheTresor();
    afficheBriques();
    afficheEnnemis();
}



function prepareTresor(){
	if(typeof prepareTresor.arguments[0]=="undefined"){
		tresor.xPos = (Math.floor(Math.random()*(380/5)))*5;
		tresor.yPos = (Math.floor(Math.random()*(380/5)))*5;
	}else{
		tresor.xPos = prepareTresor.arguments[0];
		tresor.yPos = prepareTresor.arguments[1];
	}
}

function preparePersonnage(args){
	if(typeof preparePersonnage.arguments[0]=="undefined"){
		character.xPos = (Math.floor(Math.random()*(380/5)))*5;
		character.yPos = 0;
		charXPosInitial = character.xPos;
		charYPosInitial = 0;
	}else{
		character.xPos = preparePersonnage.arguments[0];
		character.yPos = preparePersonnage.arguments[1];
		charXPosInitial = character.xPos;
		charYPosInitial = character.yPos;
	}
	character.direction=BAS;
}

function prepareBriques(){
	var x=0;
	var y=0;
	var i=0;
	while(i<38){
		x=(Math.floor(Math.random()*(400/20)))*20;
		y=(Math.floor(Math.random()*(400/20)))*20;
		var brique = {
			xPos: x,
			yPos: y,
	    	width: 20,
	    	height: 20,
			model: document.createElement("img")
		}
		if(!collision(brique, character,0) && !collision(brique, tresor,0)){
			tab_briques[i]=brique;
			nbBriques++;
			i++;
		}
	}
}

function prepareBrique(x, y){
	var brique = {
		xPos: x,
		yPos: y,
    	width: 20,
    	height: 20,
		model: document.createElement("img")
	}
	tab_briques[nbBriques]=brique;
	nbBriques++;
}

function prepareEnnemis(){
	var x=0;
	var y=0;
	var dirval=0;
	var i=0;
	var collisionBrique = false;
	var j=0;
	while(i<8){
		x=(Math.floor(Math.random()*(400/20)))*20;
		y=(Math.floor(Math.random()*(400/20)))*20;
		dir=(Math.floor(Math.random()*4));
		var ennemi={
	    	speed:3,
	    	xPos:x,
	    	yPos:y,
	    	width: 20,
	    	height: 20,
	    	direction: dir,
	    	model: document.createElement('img')
		}
		while(j<nbBriques && !collisionBrique){
			collisionBrique=collision(tab_briques[j], ennemi,0);
			j++;
		}
		if (!collisionBrique && !collision(ennemi, character,0)){
			tab_ennemis[i]=ennemi;
			ennemisXPosInitial[i]=ennemi.xPos;
			ennemisYPosInitial[i]=ennemi.yPos;
			ennemisDirectionInitiale[i]=ennemi.direction;
			nbEnnemis++;
			i++;
		}
		j=0;
		collisionBrique=false;
	}
}

function prepareEnnemi(x, y, dir){
	var ennemi={
    	speed:3,
    	xPos:x,
    	yPos:y,
    	width: 20,
    	height: 20,
    	direction: dir,
    	model: document.createElement('img')
	}
	tab_ennemis[nbEnnemis]=ennemi;
	ennemisXPosInitial[nbEnnemis]=ennemi.xPos;
	ennemisYPosInitial[nbEnnemis]=ennemi.yPos;
	ennemisDirectionInitiale[nbEnnemis]=ennemi.direction;
	nbEnnemis++;

}







function draw(){
	affichePersonage();
	afficheEnnemis();
	window.scrollTo(Math.min(character.xPos*zoom-(window.innerWidth/2)+10*zoom, 400*zoom-(window.innerWidth/2)), Math.min(character.yPos*zoom-(window.innerHeight/2)+10*zoom, 400*zoom-(window.innerHeight/2)));
}

function affichePersonage(){
	var source = protege?"img/personnage_up_up_protege.svg":"img/personnage_up_up.svg";
	character.model.style.WebkitTransition = "all .1s linear";
	character.model.style.left = (character.xPos+game_container.offsetLeft);
	character.model.style.top = (character.yPos+game_container.offsetTop);
	switch (character.direction){
		case HAUT:
			character.model.style.WebkitTransform = "rotate(0deg) scale(1,1)";
			break;
		case BAS:
			character.model.style.WebkitTransform = "rotate(180deg) scale(-1,1)";
			break;
		case GAUCHE:
			character.model.style.WebkitTransform = " rotate(-90deg) scale(1,1)";
			break;
		case DROITE:
			character.model.style.WebkitTransform = " rotate(90deg) scale(-1,1)";
			break;
		case HG:
			character.model.style.WebkitTransform = "rotate(-45deg) scale(1,1)";
			break;
		case HD:
			character.model.style.WebkitTransform = "rotate(45deg) scale(-1,1)";
			break;
		case BG:
			character.model.style.WebkitTransform = "rotate(-135deg) scale(1,1)";
			break;
		case BD:
			character.model.style.WebkitTransform = "rotate(135deg) scale(-1,1)";
			break;
	}
	character.model.src = source;
	character.model.id = "personnage";
	game_container.appendChild(character.model);
}

function afficheBriques(){
	for (var i = 0; i < nbBriques; i++) {
		tab_briques[i].model.className="brique";
		tab_briques[i].model.src="img/brick.svg";
		tab_briques[i].model.style="left:"+(tab_briques[i].xPos+game_container.offsetLeft)+";top:"+(tab_briques[i].yPos+game_container.offsetTop)+";";
		game_container.appendChild(tab_briques[i].model);
	}
}

function afficheEnnemis(){
	for (var i = 0; i <nbEnnemis; i++) {
		tab_ennemis[i].model.src="img/enemy_up.svg";
		switch (tab_ennemis[i].direction){
			case HAUT:
				tab_ennemis[i].model.style="left:"+(tab_ennemis[i].xPos+game_container.offsetLeft)+";top:"+(tab_ennemis[i].yPos+game_container.offsetTop)+";transform:rotate(0deg); WebkitTransform: 'rotate(0deg)'; transition: 100ms;";
				break;
			case BAS:
				tab_ennemis[i].model.style="left:"+(tab_ennemis[i].xPos+game_container.offsetLeft)+";top:"+(tab_ennemis[i].yPos+game_container.offsetTop)+";transform:rotate(180deg); WebkitTransform: 'rotate(180deg)'; transition: 100ms;";
				break;
			case GAUCHE:
				tab_ennemis[i].model.style="left:"+(tab_ennemis[i].xPos+game_container.offsetLeft)+";top:"+(tab_ennemis[i].yPos+game_container.offsetTop)+";transform:rotate(-90deg); WebkitTransform: 'rotate(-90deg)'; transition: 100ms;";
				break;
			case DROITE:
				tab_ennemis[i].model.style="left:"+(tab_ennemis[i].xPos+game_container.offsetLeft)+";top:"+(tab_ennemis[i].yPos+game_container.offsetTop)+";transform:rotate(90deg); WebkitTransform: 'rotate(90deg)'; transition: 100ms;";
				break;
		}
		tab_ennemis[i].model.className="ennemi";
		game_container.appendChild(tab_ennemis[i].model);
	}
}

function afficheTresor(){
	tresor.model.src = "img/tresor.svg";
	tresor.model.id = "tresor";
	tresor.model.style="left:"+(tresor.xPos+game_container.offsetLeft)+";top:"+(tresor.yPos+game_container.offsetTop)+";";
	game_container.appendChild(tresor.model);

}










function update(){
	deplacerLePersonnage();
	deplacerLesEnnemis();
	if (!protege){
		toucheUnEnnemi(character, lose);
	}
	if (collision(tresor, character, 2)){
		win();
	}
}

function toucheUnEnnemi(entite, callback){
	var collisionEnnemi = false;
	var i = 0
	while (i<tab_ennemis.length && !collisionEnnemi){
		collisionEnnemi = toucheLEnnemi(entite, tab_ennemis[i], callback);
		i++;
	}
	return collisionEnnemi;
}

function toucheLEnnemi(entite, ennemi, callback){
	if(collision(entite, ennemi, 7)){
		callback();
	}else{
		return false;
	}
}

function deplacerLesEnnemis(){
	for (var i = tab_ennemis.length - 1; i >= 0; i--) {
		deplacerLEnnemi(tab_ennemis[i]);
	}
}

function deplacerLEnnemi(ennemi){
	if(Math.floor(Math.random()*100)+1==1){
		ennemi.direction=Math.floor(Math.random()*4);
	}else{
		switch(ennemi.direction){
			case HAUT:
				if (toucheUneBriqueDenBas(ennemi) || ennemi.yPos-ennemi.speed<0) {
					ennemi.direction=Math.floor(Math.random()*4);
				}else{
					deplacerEnHaut(ennemi);
				}
				break;
			case BAS:
				if (toucheUneBriqueDenHaut(ennemi) || ennemi.yPos+ennemi.speed>380) {
					ennemi.direction=Math.floor(Math.random()*4);
				}else{
					deplacerEnBas(ennemi);
				}
				break;
			case GAUCHE:
				if (toucheUneBriqueDeLaDroite(ennemi) || ennemi.xPos-ennemi.speed<0) {
					ennemi.direction=Math.floor(Math.random()*4);
				}else{
					deplacerAGauche(ennemi);
				}
				break;
			case DROITE:
				if (toucheUneBriqueDeLaGauche(ennemi) || ennemi.xPos+ennemi.speed>380) {
					ennemi.direction=Math.floor(Math.random()*4);
				}else{
					deplacerADroite(ennemi);
				}
				break;
		}
	}
}


function deplacerLePersonnage(){
	if((keys[LEFTKEY] || keys[AKEY] || keys[QKEY]) && !(keys[RIGHTKEY] || keys[DKEY])){
		if((keys[UPKEY] || keys[ZKEY] || keys[WKEY]) && !(keys[DOWNKEY] || keys[SKEY])){
			character.direction = HG;
		}else if ((keys[DOWNKEY] || keys[SKEY]) && !(keys[UPKEY] || keys[ZKEY] || keys[WKEY])){
			character.direction = BG;
		} else{
			character.direction = GAUCHE;
		}
		if(!toucheUneBriqueDeLaDroite(character))
			deplacerAGauche(character);
	}
	if((keys[RIGHTKEY] || keys[DKEY]) && !(keys[LEFTKEY] || keys[AKEY] || keys[QKEY])){
		if((keys[UPKEY] || keys[ZKEY] || keys[WKEY]) && !(keys[DOWNKEY] || keys[SKEY])){
			character.direction = HD;
		}else if ((keys[DOWNKEY] || keys[SKEY]) && !(keys[UPKEY] || keys[ZKEY] || keys[WKEY])){
			character.direction = BD;
		} else{
			character.direction = DROITE;
		}
		if(!toucheUneBriqueDeLaGauche(character))
			deplacerADroite(character);
	}
	if((keys[UPKEY] || keys[ZKEY] || keys[WKEY]) && !(keys[DOWNKEY] || keys[SKEY])){
		if((keys[LEFTKEY] || keys[AKEY] || keys[QKEY]) && !(keys[RIGHTKEY] || keys[DKEY])){
			character.direction = HG;
		}else if ((keys[RIGHTKEY] || keys[DKEY]) && !(keys[LEFTKEY] || keys[AKEY] || keys[QKEY])){
			character.direction = HD;
		} else{
			character.direction = HAUT;
		}
		if(!toucheUneBriqueDenBas(character))
			deplacerEnHaut(character);
	}
	if((keys[DOWNKEY] || keys[SKEY]) && !(keys[UPKEY] || keys[ZKEY] || keys[WKEY])){
		if((keys[LEFTKEY] || keys[AKEY] || keys[QKEY]) && !(keys[RIGHTKEY] || keys[DKEY])){
			character.direction = BG;
		}else if ((keys[RIGHTKEY] || keys[DKEY]) && !(keys[LEFTKEY] || keys[AKEY] || keys[QKEY])){
			character.direction = BD;
		} else{
			character.direction = BAS;
		}
		if(!toucheUneBriqueDenHaut(character))
			deplacerEnBas(character);
	}
}





var toleranceBrique = 2;

function toucheUneBriqueDeLaGauche(entite){
	var touche=false;
	var i=0;
	while(i<nbBriques && !touche){
		touche = touche || toucheLaBriqueDeLaGauche(tab_briques[i], entite);
		i++;
	}
	return touche;
}

function toucheLaBriqueDeLaGauche(brique, entite){
	if(entite.xPos+entite.width+entite.speed>brique.xPos+toleranceBrique){
		if (entite.yPos+entite.height<=brique.yPos+toleranceBrique || entite.yPos>=brique.yPos+brique.height-toleranceBrique){
			return false
		}else{
			if(entite.xPos>=brique.xPos+brique.width-toleranceBrique){
				return false;
			}else{
				return true;
			}
		}
	}else{
		return false;
	}
}

function toucheUneBriqueDenHaut(entite){
	var touche=false;
	var i=0;
	while(i<nbBriques && !touche){
		touche = touche || toucheLaBriqueDenHaut(tab_briques[i], entite);
		i++;
	}
	return touche;
}

function toucheLaBriqueDenHaut(brique, entite){
	if(entite.yPos+entite.height+entite.speed>brique.yPos+toleranceBrique){
		if (entite.xPos+entite.width<=brique.xPos+toleranceBrique || entite.xPos>=brique.xPos+brique.width-toleranceBrique){
			return false
		}else{
			if(entite.yPos>=brique.yPos+brique.height-toleranceBrique){
				return false;
			}else{
				return true;
			}
		}
	}else{
		return false;
	}
}

function toucheUneBriqueDenBas(entite){
	var touche=false;
	var i=0;
	while(i<nbBriques && !touche){
		touche = touche || toucheLaBriqueDenBas(tab_briques[i], entite);
		i++;
	}
	return touche;
}

function toucheLaBriqueDenBas(brique, entite){
	if(entite.yPos-entite.speed<brique.yPos+brique.height-toleranceBrique){
		if (entite.xPos+entite.width<=brique.xPos+toleranceBrique || entite.xPos>=brique.xPos+brique.width-toleranceBrique){
			return false
		}else{
			if(entite.yPos+entite.height<=brique.yPos+toleranceBrique){
				return false;
			}else{
				return true;
			}
		}
	}else{
		return false;
	}
}

function toucheUneBriqueDeLaDroite(entite){
	var touche=false;
	var i=0;
	while(i<nbBriques && !touche){
		touche = touche || toucheLaBriqueDeLaDroite(tab_briques[i], entite);
		i++;
	}
	return touche;
}

function toucheLaBriqueDeLaDroite(brique, entite){
	if(entite.xPos-entite.speed<brique.xPos+brique.width-toleranceBrique){
		if (entite.yPos+entite.height<=brique.yPos+toleranceBrique || entite.yPos>=brique.yPos+brique.height-toleranceBrique){
			return false
		}else{
			if(entite.xPos+entite.width<=brique.xPos+toleranceBrique){
				return false;
			}else{
				return true;
			}
		}
	}else{
		return false;
	}
}





function deplacerAGauche(entite){
	entite.xPos-=entite.xPos-entite.speed<0?0:entite.speed;
}

function deplacerADroite(entite){
	entite.xPos+=entite.xPos+entite.speed>380?0:entite.speed;
}

function deplacerEnHaut(entite){
	entite.yPos-=entite.yPos-entite.speed<0?0:entite.speed;
}

function deplacerEnBas(entite){
	entite.yPos+=entite.yPos+entite.speed>380?0:entite.speed;
}

function collision(entite1, entite2, tolerance){
	if (entite1.xPos+entite1.width-tolerance<entite2.xPos)
		return false;
	if (entite1.xPos>entite2.xPos+entite2.width-tolerance)
		return false;
	if (entite1.yPos+entite1.height-tolerance<entite2.yPos)
		return false;
	if (entite1.yPos>entite2.yPos+entite2.height-tolerance)
		return false;
	return true;
}



var win = function(){
	if (niveauEnCours!=""){
		switch (niveauEnCours){
			case "1":
				alert("Ce coffre était un leurre des pingouins, ils n'y ont mis que des vieilleries dedans.");
				break;
			case "2":
				alert("Ce coffre était rempli d'or ! Vous voilà riches !!!");
				break;
			case "3":
				if (protection.hidden!=false)
					alert("Ce coffre renfermait donc un alpaga bleu !! Quel soulagement pour lui d'être enfin libre. Il vous indique cependant que la princesse Alpacorn a été enlevée par les pingouins.");
				else
					alert("Ce coffre renfermait donc un alpaga bleu !! Quel soulagement pour lui d'être enfin libre.");
				break;
				break;
			case "4":
				if (protection.hidden!=false)
					alert("La princesse Alpacorn ne se trouve pas dans ce coffre, où peut-elle bien être ?");
				else
					alert("La princesse Alpacorn vient vous faire un bisou sur la joue.");
				break;
			case "5":
				alert("Le coffre contenait l'emplacement du camps des pingouins, il se trouve au niveau 42 !");
				break;
			case "42":
				alert("Les pingouins ont déplacé la princesse Alpacorn dans un autre lieu, elle est désormais au niveau 124 !");
				break;
			case "124":
				alert("\"Alpert, la princesse Alpacorn est avec nous au niveau 69, si tu veux la revoir, il vous faudra venir la chercher !\n signé : les pingouins.\"");
				break;
			case "69":
				alert("\"Alpert, fais attention aux pingouins, ils veulent te tendre un piège, je t'en prie, ne viens pas me chercher au niveau 792.\nSigné : la princesse Alpacorn\"");
				break;
			case "792":
				alert("\"Alpert, la princesse Alpacorn est au niveau -12 !\n Signé : un espion\"");
				break;
			case "-12":
				if (protection.hidden!=false) 
					alert("\"FELICITATION !!!Vous avez libéré la princesse Alpacorn ! Pour vous récompenser, elle vous offre la protection ultime !! Les pingouins ne pourront plus vous faire de mal avec elle !\"");
				else
					alert("La princesse Alpacorn est fière de vous.");
				protection.hidden=false;
				break;
			default:
				break;
		}
		niveauEnCours="";
	}else{
		switch (Math.floor(Math.random()*10)+1){
			case 1:
				alert("Ce coffre était rempli d'or ! Vous voilà riches !!!");
				break;
			case 2:
				if (protection.hidden!=false)
					alert("Ce coffre renfermait donc un alpaga bleu !! Quel soulagement pour lui d'être enfin libre. Il vous indique cependant que la princesse Alpacorn a été enlevée par les pingouins.");
				else
					alert("Ce coffre renfermait donc un alpaga bleu !! Quel soulagement pour lui d'être enfin libre.");
				break;
			case 3:
				alert("Tout plein de pierres précieuses, et de bijoux se trouvaient dans ce coffre.");
				break;
			case 4:
				alert("Ce coffre est rempli de jeux !!! Alpert va pouvoir s'amuser longtemps désormais.");
				break;
			case 5:
				alert("Le saviez-vous ? il existe des niveaux allant de 1 à 5 déjà programmés !");
				break;
			case 6:
				alert("Un magnifique chapeau se trouvait dans ce coffre.");
				break;
			case 7:
				alert("Ce coffre était un leurre des pingouins, ils n'y ont mis que des vieilleries dedans.");
				break;
			case 8:
				alert("Un chaton trop mignon était enfermé das ce coffre. Comme vous l'avez sauvé, il est devenu votre meilleur ami.");
				break;
			case 9:
				if (protection.hidden!=false)
					alert("La princesse Alpacorn ne se trouve pas dans ce coffre, où peut-elle bien être ?");
				else
					alert("La princesse Alpacorn vient vous faire un bisou sur la joue.");
				break;
			case 10:
				alert("Le coffre contenait l'emplacement du camps des pingouins, il se trouve au niveau 42 !");
				break;
			default:
				alert("Un doge se trouvait dans le coffre, félicitation, vous avez votre propre shiba ! ( ͡° ͜ʖ ͡°)");
				break;
		}
	}
	character.direction=BAS;
	chargerNiveau();
	jeu_commence=false;
}

var lose = function(){
	alert("Attention ! Les pingouins vous ont eu ! ( ͡° ͜ʖ ͡°)");
	keys={};
	for (var i = nbEnnemis-1; i >= 0; i--) {
		tab_ennemis[i].xPos=ennemisXPosInitial[i];
		tab_ennemis[i].yPos=ennemisYPosInitial[i]
		tab_ennemis[i].direction=ennemisDirectionInitiale[i];
	}
	character.xPos=charXPosInitial;
	character.yPos=charYPosInitial;
	character.direction=BAS;
	jeu_commence=false;
}

var zoom=window.innerWidth/300;
//var zoom=1;
game_container.style.zoom=zoom;


document.onload = init();